#### 1. Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно

In [1]:
import numpy as np

In [4]:
a = np.arange(12, 24)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

#### 2. Cоздать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.

In [6]:
a1 = a.reshape(2, 6)
a1

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [7]:
a2 = a.reshape(3, 4)
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [8]:
a3 = a.reshape(4, 3)
a3

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [9]:
a4 = a.reshape(6, 2)
a4

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [10]:
a5 = a.reshape(12, 1)
a5

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

#### 3. Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).

In [16]:
a1 = a.reshape(-1, 6)
a1

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [17]:
a2 = a.reshape(-1, 4)
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [23]:
a3 = a.reshape(6, -1)
a3

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [21]:
a4 = a.reshape(4, -1)
a4

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [22]:
a5 = a.reshape(12, -1)
a5

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

#### 4. Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?

Ответ: нет

In [24]:
a5.ndim

2

#### 5. Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. 
Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.

In [29]:
a = np.random.randn(3, 4)
a, a.size

(array([[-1.38456192,  1.20384831, -0.71125185, -0.05888957],
        [ 0.39581171,  1.21903213,  2.01968941, -0.43433599],
        [ 1.23734254, -0.0317702 , -0.80950939,  1.54679898]]),
 12)

In [28]:
a = a.flatten()
a, a.size

(array([ 1.31173341,  0.50166821,  0.4896016 , -0.23303015, -0.35869727,
        -1.1176389 , -0.22449477,  0.1610601 , -0.7101917 , -0.57085364,
         0.01571177,  0.61507592]),
 12)

#### 6. Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.

In [30]:
a = np.arange(20, 0, -2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

#### 7. Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?


In [37]:
b = np.arange(20, 1, -2)
b

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

In [34]:
# разницы нет
np.array_equal(a, b)

True

#### 8. Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.

In [40]:
a = np.zeros((3, 2))
b = np.ones((2, 2))
a, b

(array([[0., 0.],
        [0., 0.],
        [0., 0.]]),
 array([[1., 1.],
        [1., 1.]]))

In [42]:
v = np.concatenate((a, b), axis=0)
v, v.size

(array([[0., 0.],
        [0., 0.],
        [0., 0.],
        [1., 1.],
        [1., 1.]]),
 10)

#### 9. Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?

In [43]:
a = np.arange(0, 12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [57]:
A = a.reshape(4, 3)
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [47]:
At = np.transpose(A)
At

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [50]:
B = A.dot(At)
B, B.size

(array([[  5,  14,  23,  32],
        [ 14,  50,  86, 122],
        [ 23,  86, 149, 212],
        [ 32, 122, 212, 302]]),
 16)

In [58]:
# Вычислить обратную матрицу не получится, т.к. ее определитель равен нулю
np.linalg.det(B)

0.0

#### 10. Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.

In [60]:
np.random.seed(42)

#### 11. Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно. 

In [69]:
c = np.random.uniform(0, 16, (1, 16)).flatten()
c

array([ 4.49495215,  8.68313733,  2.2547876 , 12.83515169,  1.1928103 ,
       15.79019099, 12.35591631,  3.1794509 ,  0.08835387, 13.04738286,
       11.3097175 , 11.66411469, 12.34032555,  1.18471443,  5.73545166,
        1.85390495])

#### 12. Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. Вычислите определитель, ранг и обратную матрицу D_inv для D.

In [73]:
C = c.reshape((4, 4))
C

array([[ 4.49495215,  8.68313733,  2.2547876 , 12.83515169],
       [ 1.1928103 , 15.79019099, 12.35591631,  3.1794509 ],
       [ 0.08835387, 13.04738286, 11.3097175 , 11.66411469],
       [12.34032555,  1.18471443,  5.73545166,  1.85390495]])

In [74]:
D = C * 10 + B
D

array([[ 49.94952155, 100.83137331,  45.547876  , 160.35151692],
       [ 25.92810299, 207.90190986, 209.55916309, 153.79450905],
       [ 23.88353874, 216.47382855, 262.09717502, 328.64114689],
       [155.40325547, 133.84714428, 269.35451657, 320.53904952]])

In [75]:
np.linalg.det(D)

-497090909.24762547

In [76]:
np.linalg.matrix_rank(D)

4

In [78]:
D_inv = np.linalg.inv(D)
D_inv

array([[ 0.00540758,  0.00425067, -0.01001874,  0.00552733],
       [ 0.00745658,  0.00753857, -0.0042368 , -0.00300331],
       [-0.01006416,  0.00153842,  0.00151263,  0.00274566],
       [ 0.00272176, -0.00650144,  0.00535534, -0.00061315]])

#### 13. Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, что в матрице D_inv остались только нули и единицы. С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4.  Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.

In [81]:
D_inv[D_inv > 0] = 1
D_inv[D_inv < 0] = 0
D_inv

array([[1., 1., 0., 1.],
       [1., 1., 0., 0.],
       [0., 1., 1., 1.],
       [1., 0., 1., 0.]])

In [87]:
E = np.where(D_inv == 1, B, C)
B, C, E

(array([[  5,  14,  23,  32],
        [ 14,  50,  86, 122],
        [ 23,  86, 149, 212],
        [ 32, 122, 212, 302]]),
 array([[ 4.49495215,  8.68313733,  2.2547876 , 12.83515169],
        [ 1.1928103 , 15.79019099, 12.35591631,  3.1794509 ],
        [ 0.08835387, 13.04738286, 11.3097175 , 11.66411469],
        [12.34032555,  1.18471443,  5.73545166,  1.85390495]]),
 array([[5.00000000e+00, 1.40000000e+01, 2.25478760e+00, 3.20000000e+01],
        [1.40000000e+01, 5.00000000e+01, 1.23559163e+01, 3.17945090e+00],
        [8.83538740e-02, 8.60000000e+01, 1.49000000e+02, 2.12000000e+02],
        [3.20000000e+01, 1.18471443e+00, 2.12000000e+02, 1.85390495e+00]]))